name: Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions: write-all

    runs-on: ubuntu-latest

    steps:
      - name: Prepare - Checkout
        uses: actions/checkout@v4.0.0

      - name: Prepare - Inject short Variables
        uses: rlespinasse/github-slug-action@v4.4.1

      - name: Prepare - Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.10.0

      - name: Prepare - Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Build - BUILD
        uses: docker/build-push-action@v4.2.1
        with:
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          tags: on-local

      - name: Publish - Calculate Version
        if: github.event_name != 'pull_request'
        env:
          BUILD_NUMBER: ${{ github.run_number }}
        run: |
          echo "BUILD_NUMBER=$(($BUILD_NUMBER))" >> $GITHUB_ENV

      - name: Publish - Login to Heroku Container Registry
        if: github.event_name != 'pull_request'
        run: |
          docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
        env:
          HEROKU_LOGIN: ${{ secrets.HEROKU_LOGIN }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          
      - name: Publish - Rename Tags and Push to Heroku
        if: github.event_name != 'pull_request'
        run: |
          docker tag on-local registry.heroku.com/code-slide/web
          docker push registry.heroku.com/code-slide/web
    
      - name: Publish - Release to Heroku
        if: github.event_name != 'pull_request'
        run: |
          heroku container:release web --app code-slide
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}